apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-appbundle-app-prod
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    name: in-cluster
  project: appbundle-project-prod
  source:
    path: aoa-kustomized-helm/apps-children/prod
    repoURL: https://github.com/CBOTY/argocd/
    targetRevision: HEAD