apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-dependency
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  anotations:
    argocd.argoproj.io/sybc-wave: "5"
spec:
  destination:
    namespace: helm-dependency
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: app-of-apps/helm-dependency
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}